# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Runic Scribings
description: > # this means to ignore newlines until "baseurl:"
  Notes on my various worldbuilding projects
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  runicscribe

# Build settings
markdown: kramdown
encoding: utf-8

# deployment
host: 0.0.0.0
port: 4000

